version: '3.1'

services:
  explorer_trail_db:
    image: postgres:12.3
    environment:
      - POSTGRES_DB=StemExplorer
      - POSTGRES_USER=stem
      - POSTGRES_PASSWORD=stem2020
      - POSTGRES_ROOT_PASSWORD=root_password
    volumes:
      - stem-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  explorer_trial_api:
    build:
      context: ./StemExplorerAPI
    environment:
      - PORT=5000
      - ASPNETCORE_ENVIRONMENT=Development
      - SiteHost=http://localhost:4200
      - ConnectionStrings__StemExplorer=User ID=stem;Password=stem2020;Server=explorer_trail_db;Database=StemExplorer
    ports:
      - "5000:5000"
    depends_on:
      - explorer_trail_db
    links:
      - explorer_trail_db

  explorer_trial_ui:
    build:
      context: ./stem-explorer-ng
    environment:
      - PORT=4200
      - API_ENDPOINT=http://localhost:5000/api
      - AUTH_API
    ports:
      - '4200:4200'

  explorer_trail_admin:
    build:
      context: ./admin-ng
    environment:
      - PORT=4300
      - API_ENDPOINT=http://localhost:5000/api
      - AUTH_API
    ports:
      - '4300:4300'

volumes:
  stem-data:
    external: false
